from html.parser import HTMLParser


input_string = str = ("<div><a href=\"0001-"
   "large.html\">1</a>  "
   "Max Tegmark: Life 3."
   "0 | Lex Fridman Podc"
   "ast #1</div><div><a "
   "href=\"0002-large.ht"
   "ml\">2</a>  Christof"
   " Koch: Consciousness"
   " | Lex Fridman Podca"
   "st #2</div><div><a h"
   "ref=\"0003-large.htm"
   "l\">3</a>  Steven Pi"
   "nker: AI in the Age "
   "of Reason | Lex Frid"
   "man Podcast #3</div>"
   "<div><a href=\"0004-"
   "large.html\">4</a>  "
   "Yoshua Bengio: Deep "
   "Learning | Lex Fridm"
   "an Podcast #4</div><"
   "div><a href=\"0005-l"
   "arge.html\">5</a>  V"
   "ladimir Vapnik: Stat"
   "istical Learning | L"
   "ex Fridman Podcast #"
   "5</div><div><a href="
   "\"0006-large.html\">"
   "6</a>  Guido van Ros"
   "sum: Python | Lex Fr"
   "idman Podcast #6</di"
   "v><div><a href=\"000"
   "7-large.html\">7</a>"
   "  Jeff Atwood: Stack"
   " Overflow and Coding"
   " Horror | Lex Fridma"
   "n Podcast #7</div><d"
   "iv><a href=\"0008-la"
   "rge.html\">8</a>  Er"
   "ic Schmidt: Google |"
   " Lex Fridman Podcast"
   " #8</div><div><a hre"
   "f=\"0009-large.html"
   "\">9</a>  Stuart Rus"
   "sell: Long-Term Futu"
   "re of Artificial Int"
   "elligence | Lex Frid"
   "man Podcast #9</div>"
   "<div><a href=\"0010-"
   "large.html\">10</a> "
   " Pieter Abbeel: Deep"
   " Reinforcement Learn"
   "ing | Lex Fridman Po"
   "dcast #10</div><div>"
   "<a href=\"0011-large"
   ".html\">11</a>  Juer"
   "gen Schmidhuber: God"
   "el Machines, Meta-Le"
   "arning, and LSTMs | "
   "Lex Fridman Podcast "
   "#11</div><div><a hre"
   "f=\"0012-large.html"
   "\">12</a>  Tuomas Sa"
   "ndholm: Poker and Ga"
   "me Theory | Lex Frid"
   "man Podcast #12</div"
   "><div><a href=\"0013"
   "-large.html\">13</a>"
   "  Tomaso Poggio: Bra"
   "ins, Minds, and Mach"
   "ines | Lex Fridman P"
   "odcast #13</div><div"
   "><a href=\"0014-larg"
   "e.html\">14</a>  Kyl"
   "e Vogt: Cruise Autom"
   "ation | Lex Fridman "
   "Podcast #14</div><di"
   "v><a href=\"0015-lar"
   "ge.html\">15</a>  Le"
   "slie Kaelbling: Rein"
   "forcement Learning, "
   "Planning, and Roboti"
   "cs | Lex Fridman Pod"
   "cast #15</div><div><"
   "a href=\"0016-large."
   "html\">16</a>  Eric "
   "Weinstein: Revolutio"
   "nary Ideas in Scienc"
   "e, Math, and Society"
   " | Lex Fridman Podca"
   "st #16</div><div><a "
   "href=\"0017-large.ht"
   "ml\">17</a>  Greg Br"
   "ockman: OpenAI and A"
   "GI | Lex Fridman Pod"
   "cast #17</div><div><"
   "a href=\"0018-large."
   "html\">18</a>  Elon "
   "Musk: Tesla Autopilo"
   "t | Lex Fridman Podc"
   "ast #18</div><div><a"
   " href=\"0019-large.h"
   "tml\">19</a>  Ian Go"
   "odfellow: Generative"
   " Adversarial Network"
   "s (GANs) | Lex Fridm"
   "an Podcast #19</div>"
   "<div><a href=\"0020-"
   "large.html\">20</a> "
   " Oriol Vinyals: Deep"
   "Mind AlphaStar, Star"
   "Craft, and Language "
   "| Lex Fridman Podcas"
   "t #20</div><div><a h"
   "ref=\"0021-large.htm"
   "l\">21</a>  Chris La"
   "ttner: Compilers, LL"
   "VM, Swift, TPU, and "
   "ML Accelerators | Le"
   "x Fridman Podcast #2"
   "1</div><div><a href="
   "\"0022-large.html\">"
   "22</a>  Rajat Monga:"
   " TensorFlow | Lex Fr"
   "idman Podcast #22</d"
   "iv><div><a href=\"00"
   "23-large.html\">23</"
   "a>  Gavin Miller: Ad"
   "obe Research | Lex F"
   "ridman Podcast #23</"
   "div><div><a href=\"0"
   "024-large.html\">24<"
   "/a>  Rosalind Picard"
   ": Affective Computin"
   "g, Emotion, Privacy,"
   " and Health | Lex Fr"
   "idman Podcast #24</d"
   "iv><div><a href=\"00"
   "25-large.html\">25</"
   "a>  Jeff Hawkins: Th"
   "ousand Brains Theory"
   " of Intelligence | L"
   "ex Fridman Podcast #"
   "25</div><div><a href"
   "=\"0026-large.html\""
   ">26</a>  Sean Carrol"
   "l: The Nature of the"
   " Universe, Life, and"
   " Intelligence | Lex "
   "Fridman Podcast #26<"
   "/div><div><a href=\""
   "0027-large.html\">27"
   "</a>  Kai-Fu Lee: AI"
   " Superpowers - China"
   " and Silicon Valley "
   "| Lex Fridman Podcas"
   "t #27</div><div><a h"
   "ref=\"0028-large.htm"
   "l\">28</a>  Chris Ur"
   "mson: Self-Driving C"
   "ars at Aurora, Googl"
   "e, CMU, and DARPA | "
   "Lex Fridman Podcast "
   "#28</div><div><a hre"
   "f=\"0029-large.html"
   "\">29</a>  Gustav So"
   "derstrom: Spotify | "
   "Lex Fridman Podcast "
   "#29</div><div><a hre"
   "f=\"0030-large.html"
   "\">30</a>  Kevin Sco"
   "tt: Microsoft CTO | "
   "Lex Fridman Podcast "
   "#30</div><div><a hre"
   "f=\"0031-large.html"
   "\">31</a>  George Ho"
   "tz: Comma.ai, OpenPi"
   "lot, and Autonomous "
   "Vehicles | Lex Fridm"
   "an Podcast #31</div>"
   "<div><a href=\"0032-"
   "large.html\">32</a> "
   " Paola Arlotta: Brai"
   "n Development from S"
   "tem Cell to Organoid"
   " | Lex Fridman Podca"
   "st #32</div><div><a "
   "href=\"0033-large.ht"
   "ml\">33</a>  Keoki J"
   "ackson: Lockheed Mar"
   "tin | Lex Fridman Po"
   "dcast #33</div><div>"
   "<a href=\"0034-large"
   ".html\">34</a>  Pame"
   "la McCorduck: Machin"
   "es Who Think and the"
   " Early Days of AI | "
   "Lex Fridman Podcast "
   "#34</div><div><a hre"
   "f=\"0035-large.html"
   "\">35</a>  Jeremy Ho"
   "ward: fast.ai Deep L"
   "earning Courses and "
   "Research | Lex Fridm"
   "an Podcast #35</div>"
   "<div><a href=\"0036-"
   "large.html\">36</a> "
   " Yann LeCun: Deep Le"
   "arning, ConvNets, an"
   "d Self-Supervised Le"
   "arning | Lex Fridman"
   " Podcast #36</div><d"
   "iv><a href=\"0037-la"
   "rge.html\">37</a>  V"
   "ijay Kumar: Flying R"
   "obots | Lex Fridman "
   "Podcast #37</div><di"
   "v><a href=\"0038-lar"
   "ge.html\">38</a>  Fr"
   "ançois Chollet: Kera"
   "s, Deep Learning, an"
   "d the Progress of AI"
   " | Lex Fridman Podca"
   "st #38</div><div><a "
   "href=\"0039-large.ht"
   "ml\">39</a>  Colin A"
   "ngle: iRobot CEO | L"
   "ex Fridman Podcast #"
   "39</div><div><a href"
   "=\"0040-large.html\""
   ">40</a>  Regina Barz"
   "ilay: Deep Learning "
   "for Cancer Diagnosis"
   " and Treatment | Lex"
   " Fridman Podcast #40"
   "</div><div><a href="
   "\"0041-large.html\">"
   "41</a>  Leonard Suss"
   "kind: Quantum Mechan"
   "ics, String Theory a"
   "nd Black Holes | Lex"
   " Fridman Podcast #41"
   "</div><div><a href="
   "\"0042-large.html\">"
   "42</a>  Peter Norvig"
   ": Artificial Intelli"
   "gence: A Modern Appr"
   "oach | Lex Fridman P"
   "odcast #42</div><div"
   "><a href=\"0043-larg"
   "e.html\">43</a>  Gar"
   "y Marcus: Toward a H"
   "ybrid of Deep Learni"
   "ng and Symbolic AI |"
   " Lex Fridman Podcast"
   " #43</div><div><a hr"
   "ef=\"0044-large.html"
   "\">44</a>  David Fer"
   "rucci: IBM Watson, J"
   "eopardy & Deep Conve"
   "rsations with AI | L"
   "ex Fridman Podcast #"
   "44</div><div><a href"
   "=\"0045-large.html\""
   ">45</a>  Michio Kaku"
   ": Future of Humans, "
   "Aliens, Space Travel"
   " & Physics | Lex Fri"
   "dman Podcast #45</di"
   "v><div><a href=\"004"
   "6-large.html\">46</a"
   ">  Garry Kasparov: C"
   "hess, Deep Blue, AI,"
   " and Putin | Lex Fri"
   "dman Podcast #46</di"
   "v><div><a href=\"004"
   "7-large.html\">47</a"
   ">  Sean Carroll: Qua"
   "ntum Mechanics and t"
   "he Many-Worlds Inter"
   "pretation | Lex Frid"
   "man Podcast #47</div"
   "><div><a href=\"0048"
   "-large.html\">48</a>"
   "  Bjarne Stroustrup:"
   " C++ | Lex Fridman P"
   "odcast #48</div><div"
   "><a href=\"0049-larg"
   "e.html\">49</a>  Elo"
   "n Musk: Neuralink, A"
   "I, Autopilot, and th"
   "e Pale Blue Dot | Le"
   "x Fridman Podcast #4"
   "9</div><div><a href="
   "\"0050-large.html\">"
   "50</a>  Michael Kear"
   "ns: Algorithmic Fair"
   "ness, Privacy & Ethi"
   "cs | Lex Fridman Pod"
   "cast #50</div><div><"
   "a href=\"0051-large."
   "html\">51</a>  Dava "
   "Newman: Space Explor"
   "ation, Space Suits, "
   "and Life on Mars | L"
   "ex Fridman Podcast #"
   "51</div><div><a href"
   "=\"0052-large.html\""
   ">52</a>  Gilbert Str"
   "ang: Linear Algebra,"
   " Teaching, and MIT O"
   "penCourseWare | Lex "
   "Fridman Podcast #52<"
   "/div><div><a href=\""
   "0053-large.html\">53"
   "</a>  Noam Chomsky: "
   "Language, Cognition,"
   " and Deep Learning |"
   " Lex Fridman Podcast"
   " #53</div><div><a hr"
   "ef=\"0054-large.html"
   "\">54</a>  Ray Dalio"
   ": Principles, the Ec"
   "onomic Machine, AI &"
   " the Arc of Life | L"
   "ex Fridman Podcast #"
   "54</div><div><a href"
   "=\"0055-large.html\""
   ">55</a>  Whitney Cum"
   "mings: Comedy, Robot"
   "ics, Neurology, and "
   "Love | Lex Fridman P"
   "odcast #55</div><div"
   "><a href=\"0056-larg"
   "e.html\">56</a>  Jud"
   "ea Pearl: Causal Rea"
   "soning, Counterfactu"
   "als, and the Path to"
   " AGI | Lex Fridman P"
   "odcast #56</div><div"
   "><a href=\"0057-larg"
   "e.html\">57</a>  Roh"
   "it Prasad: Amazon Al"
   "exa and Conversation"
   "al AI | Lex Fridman "
   "Podcast #57</div><di"
   "v><a href=\"0058-lar"
   "ge.html\">58</a>  Mi"
   "chael Stevens: Vsauc"
   "e | Lex Fridman Podc"
   "ast #58</div><div><a"
   " href=\"0059-large.h"
   "tml\">59</a>  Sebast"
   "ian Thrun: Flying Ca"
   "rs, Autonomous Vehic"
   "les, and Education |"
   " Lex Fridman Podcast"
   " #59</div><div><a hr"
   "ef=\"0060-large.html"
   "\">60</a>  Jim Gates"
   ": Supersymmetry, Str"
   "ing Theory and Provi"
   "ng Einstein Right | "
   "Lex Fridman Podcast "
   "#60</div><div><a hre"
   "f=\"0061-large.html"
   "\">61</a>  Melanie M"
   "itchell: Concepts, A"
   "nalogies, Common Sen"
   "se & Future of AI | "
   "Lex Fridman Podcast "
   "#61</div><div><a hre"
   "f=\"0062-large.html"
   "\">62</a>  Donald Kn"
   "uth: Algorithms, Com"
   "plexity, and The Art"
   " of Computer Program"
   "ming | Lex Fridman P"
   "odcast #62</div><div"
   "><a href=\"0063-larg"
   "e.html\">63</a>  Ste"
   "phen Kotkin: Stalin,"
   " Putin, and the Natu"
   "re of Power | Lex Fr"
   "idman Podcast #63</d"
   "iv><div><a href=\"00"
   "64-large.html\">64</"
   "a>  Grant Sanderson:"
   " 3Blue1Brown and the"
   " Beauty of Mathemati"
   "cs | Lex Fridman Pod"
   "cast #64</div><div><"
   "a href=\"0065-large."
   "html\">65</a>  Danie"
   "l Kahneman: Thinking"
   " Fast and Slow, Deep"
   " Learning, and AI | "
   "Lex Fridman Podcast "
   "#65</div><div><a hre"
   "f=\"0066-large.html"
   "\">66</a>  Ayanna Ho"
   "ward: Human-Robot In"
   "teraction & Ethics o"
   "f Safety-Critical Sy"
   "stems | Lex Fridman "
   "Podcast #66</div><di"
   "v><a href=\"0067-lar"
   "ge.html\">67</a>  Pa"
   "ul Krugman: Economic"
   "s of Innovation, Aut"
   "omation, Safety Nets"
   " & UBI | Lex Fridman"
   " Podcast #67</div><d"
   "iv><a href=\"0068-la"
   "rge.html\">68</a>  C"
   "ristos Goodrow: YouT"
   "ube Algorithm | Lex "
   "Fridman Podcast #68<"
   "/div><div><a href=\""
   "0069-large.html\">69"
   "</a>  David Chalmers"
   ": The Hard Problem o"
   "f Consciousness | Le"
   "x Fridman Podcast #6"
   "9</div><div><a href="
   "\"0070-large.html\">"
   "70</a>  Jim Keller: "
   "Moore\'s Law, Microp"
   "rocessors, and First"
   " Principles | Lex Fr"
   "idman Podcast #70</d"
   "iv><div><a href=\"00"
   "71-large.html\">71</"
   "a>  Vladimir Vapnik:"
   " Predicates, Invaria"
   "nts, and the Essence"
   " of Intelligence | L"
   "ex Fridman Podcast #"
   "71</div><div><a href"
   "=\"0072-large.html\""
   ">72</a>  Scott Aaron"
   "son: Quantum Computi"
   "ng | Lex Fridman Pod"
   "cast #72</div><div><"
   "a href=\"0073-large."
   "html\">73</a>  Andre"
   "w Ng: Deep Learning,"
   " Education, and Real"
   "-World AI | Lex Frid"
   "man Podcast #73</div"
   "><div><a href=\"0074"
   "-large.html\">74</a>"
   "  Michael I. Jordan:"
   " Machine Learning, R"
   "ecommender Systems, "
   "and Future of AI | L"
   "ex Fridman Podcast #"
   "74</div><div><a href"
   "=\"0075-large.html\""
   ">75</a>  Marcus Hutt"
   "er: Universal Artifi"
   "cial Intelligence, A"
   "IXI, and AGI | Lex F"
   "ridman Podcast #75</"
   "div><div><a href=\"0"
   "076-large.html\">76<"
   "/a>  John Hopfield: "
   "Physics View of the "
   "Mind and Neurobiolog"
   "y | Lex Fridman Podc"
   "ast #76</div><div><a"
   " href=\"0077-large.h"
   "tml\">77</a>  Alex G"
   "arland: Ex Machina, "
   "Devs, Annihilation, "
   "and the Poetry of Sc"
   "ience | Lex Fridman "
   "Podcast #77</div><di"
   "v><a href=\"0078-lar"
   "ge.html\">78</a>  An"
   "n Druyan: Cosmos, Ca"
   "rl Sagan, Voyager, a"
   "nd the Beauty of Sci"
   "ence | Lex Fridman P"
   "odcast #78</div><div"
   "><a href=\"0079-larg"
   "e.html\">79</a>  Lee"
   " Smolin: Quantum Gra"
   "vity and Einstein\'s"
   " Unfinished Revoluti"
   "on | Lex Fridman Pod"
   "cast #79</div><div><"
   "a href=\"0080-large."
   "html\">80</a>  Vital"
   "ik Buterin: Ethereum"
   ", Cryptocurrency, an"
   "d the Future of Mone"
   "y | Lex Fridman Podc"
   "ast #80</div><div><a"
   " href=\"0081-large.h"
   "tml\">81</a>  Anca D"
   "ragan: Human-Robot I"
   "nteraction and Rewar"
   "d Engineering | Lex "
   "Fridman Podcast #81<"
   "/div><div><a href=\""
   "0082-large.html\">82"
   "</a>  Simon Sinek: L"
   "eadership, Hard Work"
   ", Optimism and the I"
   "nfinite Game | Lex F"
   "ridman Podcast #82</"
   "div><div><a href=\"0"
   "083-large.html\">83<"
   "/a>  Nick Bostrom: S"
   "imulation and Superi"
   "ntelligence | Lex Fr"
   "idman Podcast #83</d"
   "iv><div><a href=\"00"
   "84-large.html\">84</"
   "a>  William MacAskil"
   "l: Effective Altruis"
   "m | Lex Fridman Podc"
   "ast #84</div><div><a"
   " href=\"0085-large.h"
   "tml\">85</a>  Roger "
   "Penrose: Physics of "
   "Consciousness and th"
   "e Infinite Universe "
   "| Lex Fridman Podcas"
   "t #85</div><div><a h"
   "ref=\"0086-large.htm"
   "l\">86</a>  David Si"
   "lver: AlphaGo, Alpha"
   "Zero, and Deep Reinf"
   "orcement Learning | "
   "Lex Fridman Podcast "
   "#86</div><div><a hre"
   "f=\"0087-large.html"
   "\">87</a>  Richard D"
   "awkins: Evolution, I"
   "ntelligence, Simulat"
   "ion, and Memes | Lex"
   " Fridman Podcast #87"
   "</div><div><a href="
   "\"0088-large.html\">"
   "88</a>  Eric Weinste"
   "in: Geometric Unity "
   "and the Call for New"
   " Ideas & Institution"
   "s | Lex Fridman Podc"
   "ast #88</div><div><a"
   " href=\"0089-large.h"
   "tml\">89</a>  Stephe"
   "n Wolfram: Cellular "
   "Automata, Computatio"
   "n, and Physics | Lex"
   " Fridman Podcast #89"
   "</div><div><a href="
   "\"0090-large.html\">"
   "90</a>  Dmitry Korki"
   "n: Computational Bio"
   "logy of Coronavirus "
   "| Lex Fridman Podcas"
   "t #90</div><div><a h"
   "ref=\"0091-large.htm"
   "l\">91</a>  Jack Dor"
   "sey: Square, Cryptoc"
   "urrency, and Artific"
   "ial Intelligence | L"
   "ex Fridman Podcast #"
   "91</div><div><a href"
   "=\"0092-large.html\""
   ">92</a>  Harry Cliff"
   ": Particle Physics a"
   "nd the Large Hadron "
   "Collider | Lex Fridm"
   "an Podcast #92</div>"
   "<div><a href=\"0093-"
   "large.html\">93</a> "
   " Daphne Koller: Biom"
   "edicine and Machine "
   "Learning | Lex Fridm"
   "an Podcast #93</div>"
   "<div><a href=\"0094-"
   "large.html\">94</a> "
   " Ilya Sutskever: Dee"
   "p Learning | Lex Fri"
   "dman Podcast #94</di"
   "v><div><a href=\"009"
   "5-large.html\">95</a"
   ">  Dawn Song: Advers"
   "arial Machine Learni"
   "ng and Computer Secu"
   "rity | Lex Fridman P"
   "odcast #95</div><div"
   "><a href=\"0096-larg"
   "e.html\">96</a>  Ste"
   "phen Schwarzman: Goi"
   "ng Big in Business, "
   "Investing, and AI | "
   "Lex Fridman Podcast "
   "#96</div><div><a hre"
   "f=\"0097-large.html"
   "\">97</a>  Sertac Ka"
   "raman: Robots That F"
   "ly and Robots That D"
   "rive | Lex Fridman P"
   "odcast #97</div><div"
   "><a href=\"0098-larg"
   "e.html\">98</a>  Kat"
   "e Darling: Social Ro"
   "botics | Lex Fridman"
   " Podcast #98</div><d"
   "iv><a href=\"0099-la"
   "rge.html\">99</a>  K"
   "arl Friston: Neurosc"
   "ience and the Free E"
   "nergy Principle | Le"
   "x Fridman Podcast #9"
   "9</div><div><a href="
   "\"0101-large.html\">"
   "101</a>  Joscha Bach"
   ": Artificial Conscio"
   "usness and the Natur"
   "e of Reality | Lex F"
   "ridman Podcast #101<"
   "/div><div><a href=\""
   "0102-large.html\">10"
   "2</a>  Steven Pressf"
   "ield: The War of Art"
   " | Lex Fridman Podca"
   "st #102</div><div><a"
   " href=\"0103-large.h"
   "tml\">103</a>  Ben G"
   "oertzel: Artificial "
   "General Intelligence"
   " | Lex Fridman Podca"
   "st #103</div><div><a"
   " href=\"0104-large.h"
   "tml\">104</a>  David"
   " Patterson: Computer"
   " Architecture and Da"
   "ta Storage | Lex Fri"
   "dman Podcast #104</d"
   "iv><div><a href=\"01"
   "05-large.html\">105<"
   "/a>  Robert Langer: "
   "Edison of Medicine |"
   " Lex Fridman Podcast"
   " #105</div><div><a h"
   "ref=\"0106-large.htm"
   "l\">106</a>  Matt Bo"
   "tvinick: Neuroscienc"
   "e, Psychology, and A"
   "I at DeepMind | Lex "
   "Fridman Podcast #106"
   "</div><div><a href="
   "\"0107-large.html\">"
   "107</a>  Peter Singe"
   "r: Suffering in Huma"
   "ns, Animals, and AI "
   "| Lex Fridman Podcas"
   "t #107</div><div><a "
   "href=\"0108-large.ht"
   "ml\">108</a>  Sergey"
   " Levine: Robotics an"
   "d Machine Learning |"
   " Lex Fridman Podcast"
   " #108</div><div><a h"
   "ref=\"0109-large.htm"
   "l\">109</a>  Brian K"
   "ernighan: UNIX, C, A"
   "WK, AMPL, and Go Pro"
   "gramming | Lex Fridm"
   "an Podcast #109</div"
   "><div><a href=\"0110"
   "-large.html\">110</a"
   ">  Jitendra Malik: C"
   "omputer Vision | Lex"
   " Fridman Podcast #11"
   "0</div><div><a href="
   "\"0111-large.html\">"
   "111</a>  Richard Kar"
   "p: Algorithms and Co"
   "mputational Complexi"
   "ty | Lex Fridman Pod"
   "cast #111</div><div>"
   "<a href=\"0112-large"
   ".html\">112</a>  Ian"
   " Hutchinson: Nuclear"
   " Fusion, Plasma Phys"
   "ics, and Religion | "
   "Lex Fridman Podcast "
   "#112</div><div><a hr"
   "ef=\"0113-large.html"
   "\">113</a>  Manolis "
   "Kellis: Human Genome"
   " and Evolutionary Dy"
   "namics | Lex Fridman"
   " Podcast #113</div><"
   "div><a href=\"0114-l"
   "arge.html\">114</a> "
   " Russ Tedrake: Under"
   "actuated Robotics, C"
   "ontrol, Dynamics and"
   " Touch | Lex Fridman"
   " Podcast #114</div><"
   "div><a href=\"0115-l"
   "arge.html\">115</a> "
   " Dileep George: Brai"
   "n-Inspired AI | Lex "
   "Fridman Podcast #115"
   "</div><div><a href="
   "\"0116-large.html\">"
   "116</a>  Sara Seager"
   ": Search for Planets"
   " and Life Outside Ou"
   "r Solar System | Lex"
   " Fridman Podcast #11"
   "6</div><div><a href="
   "\"0117-large.html\">"
   "117</a>  Sheldon Sol"
   "omon: Death and Mean"
   "ing | Lex Fridman Po"
   "dcast #117</div><div"
   "><a href=\"0118-larg"
   "e.html\">118</a>  Gr"
   "ant Sanderson: Math,"
   " Manim, Neural Netwo"
   "rks & Teaching with "
   "3Blue1Brown | Lex Fr"
   "idman Podcast #118</"
   "div><div><a href=\"0"
   "119-large.html\">119"
   "</a>  David Eagleman"
   ": Neuroplasticity an"
   "d the Livewired Brai"
   "n | Lex Fridman Podc"
   "ast #119</div><div><"
   "a href=\"0120-large."
   "html\">120</a>  Fran"
   "çois Chollet: Measur"
   "es of Intelligence |"
   " Lex Fridman Podcast"
   " #120</div><div><a h"
   "ref=\"0121-large.htm"
   "l\">121</a>  Eugenia"
   " Kuyda: Friendship w"
   "ith an AI Companion "
   "| Lex Fridman Podcas"
   "t #121</div><div><a "
   "href=\"0122-large.ht"
   "ml\">122</a>  David "
   "Fravor: UFOs, Aliens"
   ", Fighter Jets, and "
   "Aerospace Engineerin"
   "g | Lex Fridman Podc"
   "ast #122</div><div><"
   "a href=\"0123-large."
   "html\">123</a>  Mano"
   "lis Kellis: Origin o"
   "f Life, Humans, Idea"
   "s, Suffering, and Ha"
   "ppiness | Lex Fridma"
   "n Podcast #123</div>"
   "<div><a href=\"0124-"
   "large.html\">124</a>"
   "  Stephen Wolfram: F"
   "undamental Theory of"
   " Physics, Life, and "
   "the Universe | Lex F"
   "ridman Podcast #124<"
   "/div><div><a href=\""
   "0125-large.html\">12"
   "5</a>  Ryan Hall: Ma"
   "rtial Arts and the P"
   "hilosophy of Violenc"
   "e, Power, and Grace "
   "| Lex Fridman Podcas"
   "t #125</div><div><a "
   "href=\"0126-large.ht"
   "ml\">126</a>  James "
   "Gosling: Java, JVM, "
   "Emacs, and the Early"
   " Days of Computing |"
   " Lex Fridman Podcast"
   " #126</div><div><a h"
   "ref=\"0127-large.htm"
   "l\">127</a>  Joe Rog"
   "an: Fear, Love, Chao"
   "s, and the Joe Rogan"
   " Experience | Lex Fr"
   "idman Podcast #127</"
   "div><div><a href=\"0"
   "128-large.html\">128"
   "</a>  Michael Malice"
   ": Anarchy, Democracy"
   ", Libertarianism, Lo"
   "ve, and Trolling | L"
   "ex Fridman Podcast #"
   "128</div><div><a hre"
   "f=\"0129-large.html"
   "\">129</a>  Lisa Fel"
   "dman Barrett: Counte"
   "rintuitive Ideas Abo"
   "ut How the Brain Wor"
   "ks | Lex Fridman Pod"
   "cast #129</div><div>"
   "<a href=\"0130-large"
   ".html\">130</a>  Sco"
   "tt Aaronson: Computa"
   "tional Complexity an"
   "d Consciousness | Le"
   "x Fridman Podcast #1"
   "30</div><div><a href"
   "=\"0131-large.html\""
   ">131</a>  Chris Latt"
   "ner: The Future of C"
   "omputing and Program"
   "ming Languages | Lex"
   " Fridman Podcast #13"
   "1</div><div><a href="
   "\"0132-large.html\">"
   "132</a>  George Hotz"
   ": Hacking the Simula"
   "tion & Learning to D"
   "rive with Neural Net"
   "s | Lex Fridman Podc"
   "ast #132</div><div><"
   "a href=\"0133-large."
   "html\">133</a>  Mano"
   "lis Kellis: Biology "
   "of Disease | Lex Fri"
   "dman Podcast #133</d"
   "iv><div><a href=\"01"
   "34-large.html\">134<"
   "/a>  Eric Weinstein:"
   " On the Nature of Go"
   "od and Evil, Genius "
   "and Madness | Lex Fr"
   "idman Podcast #134</"
   "div><div><a href=\"0"
   "135-large.html\">135"
   "</a>  Charles Isbell"
   ": Computing, Interac"
   "tive AI, and Race in"
   " America | Lex Fridm"
   "an Podcast #135</div"
   "><div><a href=\"0136"
   "-large.html\">136</a"
   ">  Dan Carlin: Hardc"
   "ore History | Lex Fr"
   "idman Podcast #136</"
   "div><div><a href=\"0"
   "137-large.html\">137"
   "</a>  Alex Filippenk"
   "o: Supernovae, Dark "
   "Energy, Aliens & the"
   " Expanding Universe "
   "| Lex Fridman Podcas"
   "t #137</div><div><a "
   "href=\"0138-large.ht"
   "ml\">138</a>  Yaron "
   "Brook: Ayn Rand and "
   "the Philosophy of Ob"
   "jectivism | Lex Frid"
   "man Podcast #138</di"
   "v><div><a href=\"013"
   "9-large.html\">139</"
   "a>  Andrew Huberman:"
   " Neuroscience of Opt"
   "imal Performance | L"
   "ex Fridman Podcast #"
   "139</div><div><a hre"
   "f=\"0140-large.html"
   "\">140</a>  Lisa Fel"
   "dman Barrett: Love, "
   "Evolution, and the H"
   "uman Brain | Lex Fri"
   "dman Podcast #140</d"
   "iv><div><a href=\"01"
   "41-large.html\">141<"
   "/a>  Erik Brynjolfss"
   "on: Economics of AI,"
   " Social Networks, an"
   "d Technology | Lex F"
   "ridman Podcast #141<"
   "/div><div><a href=\""
   "0142-large.html\">14"
   "2</a>  Manolis Kelli"
   "s: Meaning of Life, "
   "the Universe, and Ev"
   "erything | Lex Fridm"
   "an Podcast #142</div"
   "><div><a href=\"0143"
   "-large.html\">143</a"
   ">  John Clarke: The "
   "Art of Fighting and "
   "the Pursuit of Excel"
   "lence | Lex Fridman "
   "Podcast #143</div><d"
   "iv><a href=\"0144-la"
   "rge.html\">144</a>  "
   "Michael Littman: Rei"
   "nforcement Learning "
   "and the Future of AI"
   " | Lex Fridman Podca"
   "st #144</div><div><a"
   " href=\"0145-large.h"
   "tml\">145</a>  Matth"
   "ew Johnson: Psychede"
   "lics | Lex Fridman P"
   "odcast #145</div><di"
   "v><a href=\"0146-lar"
   "ge.html\">146</a>  M"
   "ichael Mina: Rapid T"
   "esting, Viruses, and"
   " the Engineering Min"
   "dset | Lex Fridman P"
   "odcast #146</div><di"
   "v><a href=\"0147-lar"
   "ge.html\">147</a>  D"
   "mitri Dolgov: Waymo "
   "and the Future of Se"
   "lf-Driving Cars | Le"
   "x Fridman Podcast #1"
   "47</div><div><a href"
   "=\"0148-large.html\""
   ">148</a>  Charles Is"
   "bell and Michael Lit"
   "tman: Machine Learni"
   "ng and Education | L"
   "ex Fridman Podcast #"
   "148</div><div><a hre"
   "f=\"0149-large.html"
   "\">149</a>  Diana Wa"
   "lsh Pasulka: Aliens,"
   " Technology, Religio"
   "n & the Nature of Be"
   "lief | Lex Fridman P"
   "odcast #149</div><di"
   "v><a href=\"0150-lar"
   "ge.html\">150</a>  M"
   "ichael Malice: The W"
   "hite Pill, Freedom, "
   "Hope, and Happiness "
   "Amidst Chaos | Lex F"
   "ridman Podcast #150<"
   "/div><div><a href=\""
   "0151-large.html\">15"
   "1</a>  Dan Kokotov: "
   "Speech Recognition w"
   "ith AI and Humans | "
   "Lex Fridman Podcast "
   "#151</div><div><a hr"
   "ef=\"0152-large.html"
   "\">152</a>  Dan Gabl"
   "e: Olympic Wrestling"
   ", Mental Toughness &"
   " the Making of Champ"
   "ions | Lex Fridman P"
   "odcast #152</div><di"
   "v><a href=\"0153-lar"
   "ge.html\">153</a>  D"
   "mitry Korkin: Evolut"
   "ion of Proteins, Vir"
   "uses, Life, and AI |"
   " Lex Fridman Podcast"
   " #153</div><div><a h"
   "ref=\"0154-large.htm"
   "l\">154</a>  Avi Loe"
   "b: Aliens, Black Hol"
   "es, and the Mystery "
   "of the Oumuamua | Le"
   "x Fridman Podcast #1"
   "54</div><div><a href"
   "=\"0155-large.html\""
   ">155</a>  Max Tegmar"
   "k: AI and Physics | "
   "Lex Fridman Podcast "
   "#155</div><div><a hr"
   "ef=\"0156-large.html"
   "\">156</a>  Tim Dill"
   "on: Comedy, Power, C"
   "onspiracy Theories, "
   "and Freedom | Lex Fr"
   "idman Podcast #156</"
   "div><div><a href=\"0"
   "157-large.html\">157"
   "</a>  Natalya Bailey"
   ": Rocket Engines and"
   " Electric Spacecraft"
   " Propulsion | Lex Fr"
   "idman Podcast #157</"
   "div><div><a href=\"0"
   "158-large.html\">158"
   "</a>  Zev Weinstein:"
   " The Next Generation"
   " of Big Ideas and Br"
   "ave Minds | Lex Frid"
   "man Podcast #158</di"
   "v><div><a href=\"015"
   "9-large.html\">159</"
   "a>  Richard Craib: W"
   "allStreetBets, Numer"
   "ai, and the Future o"
   "f Stock Trading | Le"
   "x Fridman Podcast #1"
   "59</div><div><a href"
   "=\"0160-large.html\""
   ">160</a>  Brendan Ei"
   "ch: JavaScript, Fire"
   "fox, Mozilla, and Br"
   "ave | Lex Fridman Po"
   "dcast #160</div><div"
   "><a href=\"0161-larg"
   "e.html\">161</a>  Ja"
   "son Calacanis: Start"
   "ups, Angel Investing"
   ", Capitalism, and Fr"
   "iendship | Lex Fridm"
   "an Podcast #161</div"
   "><div><a href=\"0162"
   "-large.html\">162</a"
   ">  Jim Keller: The F"
   "uture of Computing, "
   "AI, Life, and Consci"
   "ousness | Lex Fridma"
   "n Podcast #162</div>"
   "<div><a href=\"0163-"
   "large.html\">163</a>"
   "  Eric Weinstein: Di"
   "fficult Conversation"
   "s, Freedom of Speech"
   ", and Physics | Lex "
   "Fridman Podcast #163"
   "</div><div><a href="
   "\"0164-large.html\">"
   "164</a>  Andrew Hube"
   "rman: Sleep, Dreams,"
   " Creativity, Fasting"
   ", and Neuroplasticit"
   "y | Lex Fridman Podc"
   "ast #164</div><div><"
   "a href=\"0165-large."
   "html\">165</a>  Josh"
   " Barnett: Philosophy"
   " of Violence, Power,"
   " and the Martial Art"
   "s | Lex Fridman #165"
   "</div><div><a href="
   "\"0166-large.html\">"
   "166</a>  Cal Newport"
   ": Deep Work, Focus, "
   "Productivity, Email,"
   " and Social Media | "
   "Lex Fridman Podcast "
   "#166</div><div><a hr"
   "ef=\"0167-large.html"
   "\">167</a>  Saagar E"
   "njeti: Politics, His"
   "tory, and Power | Le"
   "x Fridman Podcast #1"
   "67</div><div><a href"
   "=\"0168-large.html\""
   ">168</a>  Silvio Mic"
   "ali: Cryptocurrency,"
   " Blockchain, Algoran"
   "d, Bitcoin & Ethereu"
   "m | Lex Fridman Podc"
   "ast #168</div><div><"
   "a href=\"0169-large."
   "html\">169</a>  Ryan"
   " Hall: Solving Marti"
   "al Arts from First P"
   "rinciples | Lex Frid"
   "man Podcast #169</di"
   "v><div><a href=\"017"
   "0-large.html\">170</"
   "a>  Ronald Sullivan:"
   " The Ideal of Justic"
   "e in the Face of Con"
   "troversy and Evil | "
   "Lex Fridman Podcast "
   "#170</div><div><a hr"
   "ef=\"0171-large.html"
   "\">171</a>  Anthony "
   "Pompliano: Bitcoin |"
   " Lex Fridman Podcast"
   " #171</div><div><a h"
   "ref=\"0172-large.htm"
   "l\">172</a>  Ryan Sc"
   "hiller: Librex and t"
   "he Free Exchange of "
   "Ideas on College Cam"
   "puses | Lex Fridman "
   "Podcast #172</div><d"
   "iv><a href=\"0173-la"
   "rge.html\">173</a>  "
   "Nic Carter: Bitcoin "
   "Core Values, Layered"
   " Scaling, and Blocks"
   "ize Debates | Lex Fr"
   "idman Podcast #173</"
   "div><div><a href=\"0"
   "174-large.html\">174"
   "</a>  Tyler Cowen: E"
   "conomic Growth & the"
   " Fight Against Confo"
   "rmity & Mediocrity |"
   " Lex Fridman Podcast"
   " #174</div><div><a h"
   "ref=\"0175-large.htm"
   "l\">175</a>  Yannis "
   "Pappas: History and "
   "Comedy | Lex Fridman"
   " Podcast #175</div><"
   "div><a href=\"0176-l"
   "arge.html\">176</a> "
   " Robert Breedlove: P"
   "hilosophy of Bitcoin"
   " from First Principl"
   "es | Lex Fridman Pod"
   "cast #176</div><div>"
   "<a href=\"0177-large"
   ".html\">177</a>  Ris"
   "to Miikkulainen: Neu"
   "roevolution and Evol"
   "utionary Computation"
   " | Lex Fridman Podca"
   "st #177</div><div><a"
   " href=\"0178-large.h"
   "tml\">178</a>  Micha"
   "el Malice and Yaron "
   "Brook: Ayn Rand, Hum"
   "an Nature, and Anarc"
   "hy | Lex Fridman Pod"
   "cast #178</div><div>"
   "<a href=\"0179-large"
   ".html\">179</a>  Geo"
   "rges St-Pierre: The "
   "Science of Fighting "
   "| Lex Fridman Podcas"
   "t #179</div><div><a "
   "href=\"0180-large.ht"
   "ml\">180</a>  Jeremi"
   " Suri: History of Am"
   "erican Power | Lex F"
   "ridman Podcast #180<"
   "/div><div><a href=\""
   "0181-large.html\">18"
   "1</a>  Sergey Nazaro"
   "v: Chainlink, Smart "
   "Contracts, and Oracl"
   "e Networks | Lex Fri"
   "dman Podcast #181</d"
   "iv><div><a href=\"01"
   "82-large.html\">182<"
   "/a>  John Danaher: T"
   "he Path to Mastery i"
   "n Jiu Jitsu, Grappli"
   "ng, Judo, and MMA | "
   "Lex Fridman Podcast "
   "#182</div><div><a hr"
   "ef=\"0183-large.html"
   "\">183</a>  Po-Shen "
   "Loh: Mathematics, Ma"
   "th Olympiad, Combina"
   "torics & Contact Tra"
   "cing | Lex Fridman P"
   "odcast #183</div><di"
   "v><a href=\"0184-lar"
   "ge.html\">184</a>  K"
   "atherine de Kleer: P"
   "lanets, Moons, Aster"
   "oids & Life in Our S"
   "olar System | Lex Fr"
   "idman Podcast #184</"
   "div><div><a href=\"0"
   "185-large.html\">185"
   "</a>  Sam Harris: Co"
   "nsciousness, Free Wi"
   "ll, Psychedelics, AI"
   ", UFOs, and Meaning "
   "| Lex Fridman Podcas"
   "t #185</div><div><a "
   "href=\"0186-large.ht"
   "ml\">186</a>  Bryan "
   "Johnson: Kernel Brai"
   "n-Computer Interface"
   "s | Lex Fridman Podc"
   "ast #186</div><div><"
   "a href=\"0187-large."
   "html\">187</a>  Fran"
   "k Wilczek: Physics o"
   "f Quarks, Dark Matte"
   "r, Complexity, Life "
   "& Aliens | Lex Fridm"
   "an Podcast #187</div"
   "><div><a href=\"0188"
   "-large.html\">188</a"
   ">  Vitalik Buterin: "
   "Ethereum 2.0 | Lex F"
   "ridman Podcast #188<"
   "/div><div><a href=\""
   "0189-large.html\">18"
   "9</a>  David Sinclai"
   "r: Extending the Hum"
   "an Lifespan Beyond 1"
   "00 Years | Lex Fridm"
   "an Podcast #189</div"
   "><div><a href=\"0190"
   "-large.html\">190</a"
   ">  Jordan Ellenberg:"
   " Mathematics of High"
   "-Dimensional Shapes "
   "and Geometries | Lex"
   " Fridman Podcast #19"
   "0</div><div><a href="
   "\"0191-large.html\">"
   "191</a>  Daniel Schm"
   "achtenberger: Steeri"
   "ng Civilization Away"
   " from Self-Destructi"
   "on | Lex Fridman Pod"
   "cast #191</div><div>"
   "<a href=\"0192-large"
   ".html\">192</a>  Cha"
   "rles Hoskinson: Card"
   "ano | Lex Fridman Po"
   "dcast #192</div><div"
   "><a href=\"0193-larg"
   "e.html\">193</a>  Ro"
   "b Reid: The Existent"
   "ial Threat of Engine"
   "ered Viruses and Lab"
   " Leaks | Lex Fridman"
   " Podcast #193</div><"
   "div><a href=\"0194-l"
   "arge.html\">194</a> "
   " Bret Weinstein: Tru"
   "th, Science, and Cen"
   "sorship in the Time "
   "of a Pandemic | Lex "
   "Fridman Podcast #194"
   "</div><div><a href="
   "\"0195-large.html\">"
   "195</a>  Clara Sousa"
   "-Silva: Searching fo"
   "r Signs of Life on V"
   "enus and Other Plane"
   "ts | Lex Fridman Pod"
   "cast #195</div><div>"
   "<a href=\"0196-large"
   ".html\">196</a>  Yeo"
   "nmi Park: North Kore"
   "a | Lex Fridman Podc"
   "ast #196</div><div><"
   "a href=\"0197-large."
   "html\">197</a>  Jock"
   "o Willink: War, Lead"
   "ership, and Discipli"
   "ne | Lex Fridman Pod"
   "cast #197</div><div>"
   "<a href=\"0198-large"
   ".html\">198</a>  Sar"
   "a Walker: The Origin"
   " of Life on Earth an"
   "d Alien Worlds | Lex"
   " Fridman Podcast #19"
   "8</div><div><a href="
   "\"0199-large.html\">"
   "199</a>  Roger Reave"
   "s: Smuggling Drugs f"
   "or Pablo Escobar and"
   " the Medellin Cartel"
   " | Lex Fridman Podca"
   "st #199</div><div><a"
   " href=\"0200-large.h"
   "tml\">200</a>  Micha"
   "el Malice: Totalitar"
   "ianism and Anarchy |"
   " Lex Fridman Podcast"
   " #200</div><div><a h"
   "ref=\"0201-large.htm"
   "l\">201</a>  Konstan"
   "tin Batygin: Planet "
   "9 and the Edge of Ou"
   "r Solar System | Lex"
   " Fridman Podcast #20"
   "1</div><div><a href="
   "\"0202-large.html\">"
   "202</a>  Rick Doblin"
   ": Psychedelics | Lex"
   " Fridman Podcast #20"
   "2</div><div><a href="
   "\"0203-large.html\">"
   "203</a>  Anya Fernal"
   "d: Regenerative Farm"
   "ing and the Art of C"
   "ooking Meat | Lex Fr"
   "idman Podcast #203</"
   "div><div><a href=\"0"
   "204-large.html\">204"
   "</a>  Cumrun Vafa: S"
   "tring Theory | Lex F"
   "ridman Podcast #204<"
   "/div><div><a href=\""
   "0205-large.html\">20"
   "5</a>  Zach Bitter: "
   "Ultramarathon Runnin"
   "g | Lex Fridman Podc"
   "ast #205</div><div><"
   "a href=\"0206-large."
   "html\">206</a>  Isha"
   "n Misra: Self-Superv"
   "ised Deep Learning i"
   "n Computer Vision | "
   "Lex Fridman Podcast "
   "#206</div><div><a hr"
   "ef=\"0207-large.html"
   "\">207</a>  Chris Du"
   "ffin: The Mad Scient"
   "ist of Strength | Le"
   "x Fridman Podcast #2"
   "07</div><div><a href"
   "=\"0208-large.html\""
   ">208</a>  Jeff Hawki"
   "ns: The Thousand Bra"
   "ins Theory of Intell"
   "igence | Lex Fridman"
   " Podcast #208</div><"
   "div><a href=\"0209-l"
   "arge.html\">209</a> "
   " Luís and João Batal"
   "ha: Fermat\'s Librar"
   "y and the Art of Stu"
   "dying Papers | Lex F"
   "ridman Podcast #209<"
   "/div><div><a href=\""
   "0210-large.html\">21"
   "0</a>  Matt Walker: "
   "Sleep | Lex Fridman "
   "Podcast #210</div><d"
   "iv><a href=\"0211-la"
   "rge.html\">211</a>  "
   "Brian Muraresku: The"
   " Secret History of P"
   "sychedelics | Lex Fr"
   "idman Podcast #211</"
   "div><div><a href=\"0"
   "212-large.html\">212"
   "</a>  Joscha Bach: N"
   "ature of Reality, Dr"
   "eams, and Consciousn"
   "ess | Lex Fridman Po"
   "dcast #212</div><div"
   "><a href=\"0213-larg"
   "e.html\">213</a>  Ba"
   "rry Barish: Gravitat"
   "ional Waves and the "
   "Most Precise Device "
   "Ever Built | Lex Fri"
   "dman Podcast #213</d"
   "iv><div><a href=\"02"
   "14-large.html\">214<"
   "/a>  Jed Buchwald: I"
   "saac Newton and the "
   "Philosophy of Scienc"
   "e | Lex Fridman Podc"
   "ast #214</div><div><"
   "a href=\"0215-large."
   "html\">215</a>  Wojc"
   "iech Zaremba: OpenAI"
   " Codex, GPT-3, Robot"
   "ics, and the Future "
   "of AI | Lex Fridman "
   "Podcast #215</div><d"
   "iv><a href=\"0216-la"
   "rge.html\">216</a>  "
   "Vincent Racaniello: "
   "Viruses and Vaccines"
   " | Lex Fridman Podca"
   "st #216</div><div><a"
   " href=\"0217-large.h"
   "tml\">217</a>  Rodne"
   "y Brooks: Robotics |"
   " Lex Fridman Podcast"
   " #217</div><div><a h"
   "ref=\"0218-large.htm"
   "l\">218</a>  Jaron L"
   "anier: Virtual Reali"
   "ty, Social Media & t"
   "he Future of Humans "
   "and AI | Lex Fridman"
   " Podcast #218</div><"
   "div><a href=\"0219-l"
   "arge.html\">219</a> "
   " Donald Knuth: Progr"
   "amming, Algorithms, "
   "Hard Problems & the "
   "Game of Life | Lex F"
   "ridman Podcast #219<"
   "/div><div><a href=\""
   "0220-large.html\">22"
   "0</a>  Niels Jorgens"
   "en: New York Firefig"
   "hters and the Heroes"
   " of 9/11 | Lex Fridm"
   "an Podcast #220</div"
   "><div><a href=\"0221"
   "-large.html\">221</a"
   ">  Douglas Lenat: Cy"
   "c and the Quest to S"
   "olve Common Sense Re"
   "asoning in AI | Lex "
   "Fridman Podcast #221"
   "</div><div><a href="
   "\"0222-large.html\">"
   "222</a>  Jay McClell"
   "and: Neural Networks"
   " and the Emergence o"
   "f Cognition | Lex Fr"
   "idman Podcast #222</"
   "div><div><a href=\"0"
   "223-large.html\">223"
   "</a>  Travis Stevens"
   ": Judo, Olympics, an"
   "d Mental Toughness |"
   " Lex Fridman Podcast"
   " #223</div><div><a h"
   "ref=\"0224-large.htm"
   "l\">224</a>  Travis "
   "Oliphant: NumPy, Sci"
   "Py, Anaconda, Python"
   " & Scientific Progra"
   "mming | Lex Fridman "
   "Podcast #224</div><d"
   "iv><a href=\"0225-la"
   "rge.html\">225</a>  "
   "Jeffrey Shainline: N"
   "euromorphic Computin"
   "g and Optoelectronic"
   " Intelligence | Lex "
   "Fridman Podcast #225"
   "</div><div><a href="
   "\"0226-large.html\">"
   "226</a>  Jo Boaler: "
   "How to Learn Math | "
   "Lex Fridman Podcast "
   "#226</div><div><a hr"
   "ef=\"0227-large.html"
   "\">227</a>  Sean Kel"
   "ly: Existentialism, "
   "Nihilism, and the Se"
   "arch for Meaning | L"
   "ex Fridman Podcast #"
   "227</div><div><a hre"
   "f=\"0228-large.html"
   "\">228</a>  RZA: Wu-"
   "Tang Clan, Kung Fu, "
   "Chess, God, Life, an"
   "d Death | Lex Fridma"
   "n Podcast #228</div>"
   "<div><a href=\"0229-"
   "large.html\">229</a>"
   "  Richard Wrangham: "
   "Violence, Sex, and F"
   "ire in Human Evoluti"
   "on | Lex Fridman Pod"
   "cast #229</div><div>"
   "<a href=\"0230-large"
   ".html\">230</a>  Kel"
   "si Sheren: War, Arti"
   "llery, PTSD, and Lov"
   "e | Lex Fridman Podc"
   "ast #230</div><div><"
   "a href=\"0231-large."
   "html\">231</a>  Alex"
   " Gladstein: Bitcoin,"
   " Authoritarianism, a"
   "nd Human Rights | Le"
   "x Fridman Podcast #2"
   "31</div><div><a href"
   "=\"0232-large.html\""
   ">232</a>  Brian Gree"
   "ne: Quantum Gravity,"
   " The Big Bang, Alien"
   "s, Death, and Meanin"
   "g | Lex Fridman Podc"
   "ast #232</div><div><"
   "a href=\"0233-large."
   "html\">233</a>  Carl"
   " Hart: Heroin, Cocai"
   "ne, MDMA, Alcohol & "
   "the Role of Drugs in"
   " Society | Lex Fridm"
   "an Podcast #233</div"
   "><div><a href=\"0234"
   "-large.html\">234</a"
   ">  Stephen Wolfram: "
   "Complexity and the F"
   "abric of Reality | L"
   "ex Fridman Podcast #"
   "234</div><div><a hre"
   "f=\"0235-large.html"
   "\">235</a>  Michael "
   "Mina: Rapid COVID Te"
   "sting | Lex Fridman "
   "Podcast #235</div><d"
   "iv><a href=\"0236-la"
   "rge.html\">236</a>  "
   "Jimmy Pedro: Judo an"
   "d the Forging of Cha"
   "mpions | Lex Fridman"
   " Podcast #236</div><"
   "div><a href=\"0237-l"
   "arge.html\">237</a> "
   " Steve Viscelli: Tru"
   "cking and the Declin"
   "e of the American Dr"
   "eam | Lex Fridman Po"
   "dcast #237</div><div"
   "><a href=\"0238-larg"
   "e.html\">238</a>  Fr"
   "ancis Collins: Natio"
   "nal Institutes of He"
   "alth (NIH) | Lex Fri"
   "dman Podcast #238</d"
   "iv><div><a href=\"02"
   "39-large.html\">239<"
   "/a>  Niall Ferguson:"
   " History of Money, P"
   "ower, War, and Truth"
   " | Lex Fridman Podca"
   "st #239</div><div><a"
   " href=\"0240-large.h"
   "tml\">240</a>  Neal "
   "Stephenson: Sci-Fi, "
   "Space, Aliens, AI, V"
   "R & the Future of Hu"
   "manity | Lex Fridman"
   " Podcast #240</div><"
   "div><a href=\"0241-l"
   "arge.html\">241</a> "
   " Boris Sofman: Waymo"
   ", Cozmo, Self-Drivin"
   "g Cars, and the Futu"
   "re of Robotics | Lex"
   " Fridman Podcast #24"
   "1</div><div><a href="
   "\"0242-large.html\">"
   "242</a>  Ben Askren:"
   " Wrestling and MMA |"
   " Lex Fridman Podcast"
   " #242</div><div><a h"
   "ref=\"0243-large.htm"
   "l\">243</a>  Kevin S"
   "ystrom: Instagram | "
   "Lex Fridman Podcast "
   "#243</div><div><a hr"
   "ef=\"0244-large.html"
   "\">244</a>  Robert C"
   "rews: Afghanistan, T"
   "aliban, Bin Laden, a"
   "nd War in the Middle"
   " East | Lex Fridman "
   "Podcast #244</div><d"
   "iv><a href=\"0245-la"
   "rge.html\">245</a>  "
   "Tom Brands: Iowa Wre"
   "stling | Lex Fridman"
   " Podcast #245</div><"
   "div><a href=\"0246-l"
   "arge.html\">246</a> "
   " Peter Woit: Theorie"
   "s of Everything & Wh"
   "y String Theory is N"
   "ot Even Wrong | Lex "
   "Fridman Podcast #246"
   "</div><div><a href="
   "\"0247-large.html\">"
   "247</a>  Jamie Metzl"
   ": Lab Leak Theory | "
   "Lex Fridman Podcast "
   "#247</div><div><a hr"
   "ef=\"0248-large.html"
   "\">248</a>  Norman N"
   "aimark: Genocide, St"
   "alin, Hitler, Mao, a"
   "nd Absolute Power | "
   "Lex Fridman Podcast "
   "#248</div><div><a hr"
   "ef=\"0249-large.html"
   "\">249</a>  Albert B"
   "ourla: Pfizer CEO | "
   "Lex Fridman Podcast "
   "#249</div><div><a hr"
   "ef=\"0250-large.html"
   "\">250</a>  Peter Wa"
   "ng: Python and the S"
   "ource Code of Humans"
   ", Computers, and Rea"
   "lity | Lex Fridman P"
   "odcast #250</div><di"
   "v><a href=\"0251-lar"
   "ge.html\">251</a>  R"
   "ay Dalio: Money, Pow"
   "er, and the Collapse"
   " of Empires | Lex Fr"
   "idman Podcast #251</"
   "div><div><a href=\"0"
   "252-large.html\">252"
   "</a>  Elon Musk: Spa"
   "ceX, Mars, Tesla Aut"
   "opilot, Self-Driving"
   ", Robotics, and AI |"
   " Lex Fridman Podcast"
   " #252</div><div><a h"
   "ref=\"0253-large.htm"
   "l\">253</a>  Michael"
   " Malice: New Year\'s"
   " Special | Lex Fridm"
   "an Podcast #253</div"
   "><div><a href=\"0254"
   "-large.html\">254</a"
   ">  Jay Bhattacharya:"
   " The Case Against Lo"
   "ckdowns | Lex Fridma"
   "n Podcast #254</div>"
   "<div><a href=\"0255-"
   "large.html\">255</a>"
   "  Mark Normand: Come"
   "dy! | Lex Fridman Po"
   "dcast #255</div><div"
   "><a href=\"0256-larg"
   "e.html\">256</a>  Na"
   "tionalism Debate: Ya"
   "ron Brook and Yoram "
   "Hazony | Lex Fridman"
   " Podcast #256</div><"
   "div><a href=\"0257-l"
   "arge.html\">257</a> "
   " Brian Keating: Cosm"
   "ology, Astrophysics,"
   " Aliens & Losing the"
   " Nobel Prize | Lex F"
   "ridman Podcast #257<"
   "/div><div><a href=\""
   "0258-large.html\">25"
   "8</a>  Yann LeCun: D"
   "ark Matter of Intell"
   "igence and Self-Supe"
   "rvised Learning | Le"
   "x Fridman Podcast #2"
   "58</div><div><a href"
   "=\"0259-large.html\""
   ">259</a>  Thomas Tul"
   "l: From Batman Dark "
   "Knight Trilogy to AI"
   " and The Rolling Sto"
   "nes | Lex Fridman Po"
   "dcast #259</div><div"
   "><a href=\"0260-larg"
   "e.html\">260</a>  Ge"
   "orges St-Pierre, Joh"
   "n Danaher & Gordon R"
   "yan: The Greatest of"
   " All Time | Lex Frid"
   "man Podcast #260</di"
   "v><div><a href=\"026"
   "1-large.html\">261</"
   "a>  Philip Goff: Con"
   "sciousness, Panpsych"
   "ism, and the Philoso"
   "phy of Mind | Lex Fr"
   "idman Podcast #261</"
   "div><div><a href=\"0"
   "262-large.html\">262"
   "</a>  Garry Nolan: U"
   "FOs and Aliens | Lex"
   " Fridman Podcast #26"
   "2</div><div><a href="
   "\"0263-large.html\">"
   "263</a>  John Abrams"
   "on: Big Pharma | Lex"
   " Fridman Podcast #26"
   "3</div><div><a href="
   "\"0264-large.html\">"
   "264</a>  Tim Urban: "
   "Elon Musk, Neuralink"
   ", AI, Aliens, and th"
   "e Future of Humanity"
   " | Lex Fridman Podca"
   "st #264</div><div><a"
   " href=\"0265-large.h"
   "tml\">265</a>  Devon"
   " Larratt: Arm Wrestl"
   "ing | Lex Fridman Po"
   "dcast #265</div><div"
   "><a href=\"0266-larg"
   "e.html\">266</a>  Ni"
   "cole Perlroth: Cyber"
   "security and the Wea"
   "pons of Cyberwar | L"
   "ex Fridman Podcast #"
   "266</div><div><a hre"
   "f=\"0267-large.html"
   "\">267</a>  Mark Zuc"
   "kerberg: Meta, Faceb"
   "ook, Instagram, and "
   "the Metaverse | Lex "
   "Fridman Podcast #267"
   "</div><div><a href="
   "\"0269-large.html\">"
   "269</a>  Lee Cronin:"
   " Origin of Life, Ali"
   "ens, Complexity, and"
   " Consciousness | Lex"
   " Fridman Podcast #26"
   "9</div><div><a href="
   "\"0270-large.html\">"
   "270</a>  David Wolpe"
   ": Judaism | Lex Frid"
   "man Podcast #270</di"
   "v><div><a href=\"027"
   "1-large.html\">271</"
   "a>  Ariel Ekblaw: Sp"
   "ace Colonization and"
   " Self-Assembling Spa"
   "ce Megastructures | "
   "Lex Fridman Podcast "
   "#271</div><div><a hr"
   "ef=\"0272-large.html"
   "\">272</a>  Brett Jo"
   "hnson: US Most Wante"
   "d Cybercriminal | Le"
   "x Fridman Podcast #2"
   "72</div><div><a href"
   "=\"0273-large.html\""
   ">273</a>  Chris Blat"
   "tman: War and Violen"
   "ce | Lex Fridman Pod"
   "cast #273</div><div>"
   "<a href=\"0274-large"
   ".html\">274</a>  Kar"
   "l Deisseroth: Depres"
   "sion, Schizophrenia,"
   " and Psychiatry | Le"
   "x Fridman Podcast #2"
   "74</div><div><a href"
   "=\"0275-large.html\""
   ">275</a>  Rick Rubin"
   ": Legendary Music Pr"
   "oducer | Lex Fridman"
   " Podcast #275</div><"
   "div><a href=\"0276-l"
   "arge.html\">276</a> "
   " Michael Saylor: Bit"
   "coin, Inflation, and"
   " the Future of Money"
   " | Lex Fridman Podca"
   "st #276</div><div><a"
   " href=\"0277-large.h"
   "tml\">277</a>  Andre"
   "w Huberman: Focus, S"
   "tress, Relationships"
   ", and Friendship | L"
   "ex Fridman Podcast #"
   "277</div><div><a hre"
   "f=\"0278-large.html"
   "\">278</a>  Skye Fit"
   "zgerald: Hunger, War"
   ", and Human Sufferin"
   "g | Lex Fridman Podc"
   "ast #278</div><div><"
   "a href=\"0279-large."
   "html\">279</a>  Alie"
   "n Debate: Sara Walke"
   "r and Lee Cronin | L"
   "ex Fridman Podcast #"
   "279</div><div><a hre"
   "f=\"0280-large.html"
   "\">280</a>  Cristian"
   "o Amon: Qualcomm CEO"
   " | Lex Fridman Podca"
   "st #280</div><div><a"
   " href=\"0281-large.h"
   "tml\">281</a>  Grime"
   "s: Music, AI, and th"
   "e Future of Humanity"
   " | Lex Fridman Podca"
   "st #281</div><div><a"
   " href=\"0284-large.h"
   "tml\">284</a>  Saife"
   "dean Ammous: Bitcoin"
   ", Anarchy, and Austr"
   "ian Economics | Lex "
   "Fridman Podcast #284"
   "</div><div><a href="
   "\"0285-large.html\">"
   "285</a>  Glenn Loury"
   ": Race, Racism, Iden"
   "tity Politics, and C"
   "ancel Culture | Lex "
   "Fridman Podcast #285"
   "</div><div><a href="
   "\"0286-large.html\">"
   "286</a>  Oliver Ston"
   "e: Vladimir Putin an"
   "d War in Ukraine | L"
   "ex Fridman Podcast #"
   "286</div><div><a hre"
   "f=\"0288-large.html"
   "\">288</a>  Sarma Me"
   "lngailis: Bad Vegan,"
   " Fraud, Prison, and "
   "Sociopathy | Lex Fri"
   "dman Podcast #288</d"
   "iv><div><a href=\"02"
   "89-large.html\">289<"
   "/a>  Stephen Kotkin:"
   " Putin, Stalin, Hitl"
   "er, Zelenskyy, and W"
   "ar in Ukraine | Lex "
   "Fridman Podcast #289"
   "</div><div><a href="
   "\"0290-large.html\">"
   "290</a>  Dan Reynold"
   "s: Imagine Dragons |"
   " Lex Fridman Podcast"
   " #290</div><div><a h"
   "ref=\"0292-large.htm"
   "l\">292</a>  Robin H"
   "anson: Alien Civiliz"
   "ations, UFOs, and th"
   "e Future of Humanity"
   " | Lex Fridman Podca"
   "st #292</div><div><a"
   " href=\"0293-large.h"
   "tml\">293</a>  Donal"
   "d Hoffman: Reality i"
   "s an Illusion - How "
   "Evolution Hid the Tr"
   "uth | Lex Fridman Po"
   "dcast #293</div><div"
   "><a href=\"0294-larg"
   "e.html\">294</a>  To"
   "ny Fadell: iPhone, i"
   "Pod, Nest, Steve Job"
   "s, Design, and Engin"
   "eering | Lex Fridman"
   " Podcast #294</div><"
   "div><a href=\"0295-l"
   "arge.html\">295</a> "
   " Richard Wolff: Marx"
   "ism and Communism | "
   "Lex Fridman Podcast "
   "#295</div><div><a hr"
   "ef=\"0296-large.html"
   "\">296</a>  Douglas "
   "Murray: Racism, Marx"
   "ism, and the War on "
   "the West | Lex Fridm"
   "an Podcast #296</div"
   "><div><a href=\"0297"
   "-large.html\">297</a"
   ">  Jonathan Reisman:"
   " The Human Body - Fr"
   "om Sex & Sperm to Ha"
   "nds & Heart | Lex Fr"
   "idman Podcast #297</"
   "div><div><a href=\"0"
   "298-large.html\">298"
   "</a>  Susan Cain: Th"
   "e Power of Introvert"
   "s and Loneliness | L"
   "ex Fridman Podcast #"
   "298</div><div><a hre"
   "f=\"0299-large.html"
   "\">299</a>  Demis Ha"
   "ssabis: DeepMind - A"
   "I, Superintelligence"
   " & the Future of Hum"
   "anity | Lex Fridman "
   "Podcast #299</div><d"
   "iv><a href=\"0300-la"
   "rge.html\">300</a>  "
   "Joe Rogan: Comedy, C"
   "ontroversy, Aliens, "
   "UFOs, Putin, CIA, an"
   "d Freedom | Lex Frid"
   "man Podcast #300</di"
   "v><div><a href=\"030"
   "1-large.html\">301</"
   "a>  Jack Barsky: KGB"
   " Spy | Lex Fridman P"
   "odcast #301</div><di"
   "v><a href=\"0302-lar"
   "ge.html\">302</a>  R"
   "ichard Haier: IQ Tes"
   "ts, Human Intelligen"
   "ce, and Group Differ"
   "ences | Lex Fridman "
   "Podcast #302</div><d"
   "iv><a href=\"0303-la"
   "rge.html\">303</a>  "
   "Steve Keen: Marxism,"
   " Capitalism, and Eco"
   "nomics | Lex Fridman"
   " Podcast #303</div><"
   "div><a href=\"0304-l"
   "arge.html\">304</a> "
   " Bishop Robert Barro"
   "n: Christianity and "
   "the Catholic Church "
   "| Lex Fridman Podcas"
   "t #304</div><div><a "
   "href=\"0305-large.ht"
   "ml\">305</a>  Martin"
   " Rees: Black Holes, "
   "Alien Life, Dark Mat"
   "ter, and the Big Ban"
   "g | Lex Fridman Podc"
   "ast #305</div><div><"
   "a href=\"0306-large."
   "html\">306</a>  Orio"
   "l Vinyals: Deep Lear"
   "ning and Artificial "
   "General Intelligence"
   " | Lex Fridman Podca"
   "st #306</div><div><a"
   " href=\"0307-large.h"
   "tml\">307</a>  Brian"
   " Armstrong: Coinbase"
   ", Cryptocurrency, an"
   "d Government Regulat"
   "ion | Lex Fridman Po"
   "dcast #307</div><div"
   "><a href=\"0308-larg"
   "e.html\">308</a>  Ry"
   "an Graves: UFOs, Fig"
   "hter Jets, and Alien"
   "s | Lex Fridman Podc"
   "ast #308</div><div><"
   "a href=\"0309-large."
   "html\">309</a>  John"
   " Carmack: Doom, Quak"
   "e, VR, AGI, Programm"
   "ing, Video Games, an"
   "d Rockets | Lex Frid"
   "man Podcast #309</di"
   "v><div><a href=\"031"
   "0-large.html\">310</"
   "a>  Andrew Bustamant"
   "e: CIA Spy | Lex Fri"
   "dman Podcast #310</d"
   "iv><div><a href=\"03"
   "11-large.html\">311<"
   "/a>  Magatte Wade: A"
   "frica, Capitalism, C"
   "ommunism, and the Fu"
   "ture of Humanity | L"
   "ex Fridman Podcast #"
   "311</div><div><a hre"
   "f=\"0312-large.html"
   "\">312</a>  Duncan T"
   "russell: Comedy, Sen"
   "tient Robots, Suffer"
   "ing, Love & Burning "
   "Man | Lex Fridman Po"
   "dcast #312</div><div"
   "><a href=\"0313-larg"
   "e.html\">313</a>  Jo"
   "rdan Peterson: Life,"
   " Death, Power, Fame,"
   " and Meaning | Lex F"
   "ridman Podcast #313<"
   "/div><div><a href=\""
   "0314-large.html\">31"
   "4</a>  Liv Boeree: P"
   "oker, Game Theory, A"
   "I, Simulation, Alien"
   "s & Existential Risk"
   " | Lex Fridman Podca"
   "st #314</div><div><a"
   " href=\"0315-large.h"
   "tml\">315</a>  Magnu"
   "s Carlsen: Greatest "
   "Chess Player of All "
   "Time | Lex Fridman P"
   "odcast #315</div><di"
   "v><a href=\"0316-lar"
   "ge.html\">316</a>  N"
   "oam Chomsky: Putin, "
   "Ukraine, China, and "
   "Nuclear War | Lex Fr"
   "idman Podcast #316</"
   "div><div><a href=\"0"
   "317-large.html\">317"
   "</a>  John Vervaeke:"
   " Meaning Crisis, Ath"
   "eism, Religion & the"
   " Search for Wisdom |"
   " Lex Fridman Podcast"
   " #317</div><div><a h"
   "ref=\"0318-large.htm"
   "l\">318</a>  Nick La"
   "ne: Origin of Life, "
   "Evolution, Aliens, B"
   "iology, and Consciou"
   "sness | Lex Fridman "
   "Podcast #318</div><d"
   "iv><a href=\"0319-la"
   "rge.html\">319</a>  "
   "Botez Sisters: Chess"
   ", Streaming, and Fam"
   "e | Lex Fridman Podc"
   "ast #319</div><div><"
   "a href=\"0320-large."
   "html\">320</a>  Chri"
   "stopher Capozzola: W"
   "orld War I, Ideology"
   ", Propaganda, and Po"
   "litics | Lex Fridman"
   " Podcast #320</div><"
   "div><a href=\"0321-l"
   "arge.html\">321</a> "
   " Ray Kurzweil: Singu"
   "larity, Superintelli"
   "gence, and Immortali"
   "ty | Lex Fridman Pod"
   "cast #321</div><div>"
   "<a href=\"0322-large"
   ".html\">322</a>  Ran"
   "a el Kaliouby: Emoti"
   "on AI, Social Robots"
   ", and Self-Driving C"
   "ars | Lex Fridman Po"
   "dcast #322</div><div"
   "><a href=\"0323-larg"
   "e.html\">323</a>  Wi"
   "ll Sasso: Comedy, MA"
   "Dtv, AI, Friendship,"
   " Madness, and Pro Wr"
   "estling | Lex Fridma"
   "n Podcast #323</div>"
   "<div><a href=\"0324-"
   "large.html\">324</a>"
   "  Daniel Negreanu: P"
   "oker | Lex Fridman P"
   "odcast #324</div><di"
   "v><a href=\"0325-lar"
   "ge.html\">325</a>  M"
   "ichael Levin: Biolog"
   "y, Life, Aliens, Evo"
   "lution, Embryogenesi"
   "s & Xenobots | Lex F"
   "ridman Podcast #325<"
   "/div>\r\n")

from html.entities import name2codepoint
dict_with_data = {}
last_known_key = ""
last_known_name = ""
lex_counter = 0

class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        # print("Start tag:", tag)
        global last_known_key
        for attr in attrs:
            if 'href' in attr:
                last_known_key = attr[1]
            # print("     attr:", attr)

    def handle_endtag(self, tag):
        # print("End tag  :", tag)
        return

    def handle_data(self, data):
        # print("We are in handle data part")
        # print("Data     :", data)
        global last_known_key
        global last_known_name
        global lex_counter
        if data.find("Lex Fridman") != -1:
            lex_counter = lex_counter + 1
            last_known_name = data
            dict_with_data[last_known_key] = last_known_name
            last_known_key = ""

    def handle_comment(self, data):
        # print("Comment  :", data)
        return

    def handle_entityref(self, name):
        c = chr(name2codepoint[name])
        # print("Named ent:", c)

    def handle_charref(self, name):
        if name.startswith('x'):
            c = chr(int(name[1:], 16))
        else:
            c = chr(int(name))
        # print("Num ent  :", c)

    def handle_decl(self, data):
        # print("Decl     :", data)
        return


parser = MyHTMLParser()
response = parser.feed(input_string)
# print(response)
print(len(dict_with_data), "Whats the length from the parsed html")
# This containts the name of the person to the file list of the podcast they were in
# along with the name of the video
name_to_file_path = {}
for (key, value) in dict_with_data.items():
    split_value = value.split(':')
    proper_name = split_value[0].strip()
    print(key, value)
    # print(proper_name)
    # Key here has the format of blah.html, lets remove the .html part here
    # and clean it up properly and format it according to our data format
    # which is episode_{blah}.vtt and insert both large and small names to it
    # cause the data dump does not have all the values yet

    # The key part is in the format 0abc_large or 0bce_small or 0cd_large/0cd_small
    # we only want to keep 3 characters in the numeric part as thats how the files are
    # indexed
    key_part = key.rstrip('.html').replace('-', '_')
    key_parts = key_part.split('_')
    if len(key_parts[0]) == 4:
        key_parts[0] = key_parts[0][1:]
    key_part = "_".join(key_parts)
    proper_file_name = f"episode_{key_part}.vtt"
    print(proper_name, proper_file_name)
    if proper_name in name_to_file_path:
        name_to_file_path[proper_name].append({'file_name': proper_file_name, 'video_name': value})
    else:
        name_to_file_path[proper_name] = [{'file_name': proper_file_name, 'video_name': value}]

# print(name_to_file_path) 

# Now that we have the key value pair for the way text should look like, lets iterate through the list and
# try to parse the input one at a time
def parse_input_file_vtt(file_name):
    lines = []
    with open(file_name, 'r') as file:
        lines = file.read()
    # print(lines)

import json
input_lines = []
with open('/tmp/document', 'r') as f:
    input_lines.append(f.read())

parsed_name_with_url_yt = json.loads(input_lines[0])
parsed_name_with_url_and_file_path = {}
count_inserted = 0
# print(parsed_name_with_url_yt)
# Now we try to get the file_name linked to the url as well, and dump that in a json
# We will then use that json to feed to firestore the embeddings and make it easy peasy
for (key, value) in name_to_file_path.items():
    print(key, value)
    for video_property in value:
        match_found = False
        for data in parsed_name_with_url_yt:
            if video_property['video_name'].strip() == data['title']:
                parsed_name_with_url_and_file_path[video_property['video_name']] = {
                    'name': key,
                    'file_name': video_property['file_name'],
                    'url': data['url'],
                    'video_name': video_property['video_name']
                }
                count_inserted = count_inserted + 1
                match_found = True
                continue
        if not match_found:
            print("No matches were found for", video_property)

print(count_inserted)
for key, value in parsed_name_with_url_and_file_path.items():
    print(key, value)
print(len(parsed_name_with_url_and_file_path))
# print(len(parsed_name_with_url_and_file_path))


# How should the text distribution look like?
# I think we should split into 2048 token lengths and send it over
# then there are entries with multiple podcasts, so while taking cosine similarity
# we try to get one from each if it comes in the top 3
# Lets dump this data to a file
with open('/tmp/parsed_text_file', 'w') as f:
    f.write(json.dumps(parsed_name_with_url_and_file_path))